name: Caller
on: 
  pull_request:

jobs:
  reusable-preview:
    name: call
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    uses: foo-1a/gha-test/.github/workflows/called.yml@main
    with: {}
    secrets:
      extra-secrets: ${{ secrets.EXTRA_SECRETS }}

  env-loading:
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - id: loadenv
        shell: bash
        run: |
          echo "::add-mask::val1"
          echo "::add-mask::val2"
          echo "loadedenv={\"VAR1\":\"val1\",\"VAR2\":\"val2\"}" >> $GITHUB_OUTPUT
        env: &hardcodedenv
          VAR3: val3
      - run: |
          env | grep VAR
        shell: bash
        env:
          <<: [*hardcodedenv]
          ${{ fromJSON(steps.loadenv.outputs.loadedenv) }}
    
