name: Caller
on: 
  pull_request:

jobs:
  reusable-preview:
    name: call
    uses: foo-1a/gha-test/.github/workflows/called.yml@main
    with: {}
    secrets:
      extra-secrets: ${{ secrets.EXTRA_SECRETS }}
