# FIXME: temporarily forked from https://github.com/primait/shared-github-actions/blob/master/.github/workflows/pulumi-preview.yml as upstream is under active development and we're affected by breaking changes

name: Reusable
on:
  workflow_call:
    secrets:
      extra-secrets:
        required: false

jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: load secrets
        uses: ./.github/actions/load-secrets
        with:
          single-secret: ${{ secrets.extra-secrets }}
      - run: env
