# FIXME: temporarily forked from https://github.com/primait/shared-github-actions/blob/master/.github/workflows/pulumi-preview.yml as upstream is under active development and we're affected by breaking changes

name: Reusable
on:
  workflow_call:
    inputs:
      gh-env:
        type: string
    secrets:
      extra-secrets:
        required: false

jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: templating extra secrets test
        run: echo somecommand ${{ secrets.extra-secrets != '' && format('--extraparam {0}', secrets.extra-secrets) || '' }}
      - name: load secrets
        uses: ./.github/actions/load-secrets
        with:
          single-secret: ${{ secrets.extra-secrets }}
      - run: env
      - run: env | grep pr
      - run: env | grep main
