name: Caller
on: 
  push:
    branches:
      - "main"

jobs:
  reusable-deploy:
    name: call
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    uses: foo-1a/gha-test/.github/workflows/called.yml@main
    with:
      gh-env: prod
    secrets:
      extra-secrets: ${{ secrets.EXTRA_SECRETS }}
