name: Caller
on: 
  push:
    branches:
      - "main"

jobs:
  reusable-deploy:
    name: call
    environment: prod
    uses: foo-1a/gha-test/.github/workflows/called.yml@main
    with: {}
    secrets:
      extra-secrets: ${{ secret.EXTRA_SECRETS }}
