name: secretformat
on: 
  workflow_dispatch:

jobs:
  reusable-preview:
    name: call
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    uses: foo-1a/gha-test/.github/workflows/called.yml@main
    with: {}
    secrets:
      extra-secrets: ${{ secrets.API_SECRET }}
  can-reference-nonexisting:
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{ secrets[DOES_NOT_EXIST] }}
  
